### ISSUE TITLE
Issue when setting Icon

### ISSUE THREAD

**Issue by theolazian** [theolazian/electron-webpack-bootstrap-fontawesome-jquery#2]
@theolazian  I'm sorry borther you!

I had another questions. How make setIcon work! The follow figure is the reason that I setIcon dot work and load img faild!(I guess!).

![image](https://user-images.githubusercontent.com/18387852/143010302-5afc7eda-5277-47d7-9a2d-45f2580145fa.png)

How make copied icon file before setIcon?  Can you give me some example.

Express my gratitude again!

_Originally posted by @findmoon in https://github.com/theolazian/electron-webpack-bootstrap-fontawesome-jquery/issues/1#issuecomment-976392751_

**Comment by theolazian** [comment]
@findmoon, I posted your issue here for the sake of clarity.

Where do you try to display this icon? If it is for your main window, I usually use the icon of the packaged electron app. So you need to set it up in the ```forge.config.js``` file.

You can find an [example here](https://github.com/aliceandbob-io/aliceandbob-desktop/blob/24ddf0e410165d235d504a53eda2381e5c5cac8e/forge.config.js), in another electron app which I maintain. 
The icon is both the icon of the app and the icon of the window. It is defined under the ```packagerConfig``` options.

Hope it helps

**Comment by theolazian** [comment]
Plus, I'm not sure you need this line 27: ```mainWindow.setIcon``` as the icon is already defined when you declare your constant ```mainWindow``` at line 14.

**Comment by findmoon** [comment]
@theolazian , I add the line 27: 'mainWindow.setIcon' only for test and locate problem, Because the icon option when declare `mainWindow` at line 14 is not work!

I had try many ways to fix this problem at line 14 by setting icon. But, it not work when run `yarn start`. So, I try add `mainWindow.setIcon`, it throw a load failed error. And then, I add `console.log` as the line 11. I think it is the cause that icon copied too late by the console info.

AND, **when I packaged this electron-forge, it will run well, no error and the icon can display ok.** So, I am sure that it is a sequence issue webpack process in the development!

I want display this icon in my main window and taskbar of windows. I had try set `packagerConfig.icon`, it also can be run well and icon display after packaging (This can omit the setting in `mainWindow.setIcon` or `new BrowserWindow`)

Although it does not affect the final application, I still hope it has a solution (It is not necessary)

AND thank you for your answers!

**Comment by findmoon** [comment]
Another question I hope to achieve is How use a local icon for `iconUrl` in `squirrel.windows`. This seem to be not possible!

**Comment by findmoon** [comment]
> @findmoon, I posted your issue here for the sake of clarity.
> 
> Where do you try to display this icon? If it is for your main window, I usually use the icon of the packaged electron app. So you need to set it up in the `forge.config.js` file.
> 
> You can find an [example here](https://github.com/aliceandbob-io/aliceandbob-desktop/blob/24ddf0e410165d235d504a53eda2381e5c5cac8e/forge.config.js), in another electron app which I maintain. The icon is both the icon of the app and the icon of the window. It is defined under the `packagerConfig` options.
> 
> Hope it helps

Thanks for you again!

The icon file copied too late seem to be find the same situation from here, [\[SOLVED\] Assets missing after packaging using file-loader #1196](https://github.com/electron-userland/electron-forge/issues/1196). And ,I had try this method, it still not work.

I am not sure if the options config mentioned in the content of above link is correct, because it is not work for me!

````js
rules.push(
  {
    test: /\.(png|jpe?g|gif|ico|svg)$/, // We will handle of these file extensions
    use: [
      {
        loader: "file-loader",
        options: {
          name: "[path][name].[ext]",
          publicPath: "..", // move up from 'main_window'
          context: "src", // set relative working folder to src
        },
      }
    ]
  },
);
````

I implement copied icon by using copy-webpack-plugin

![https://user-images.githubusercontent.com/18387852/143019663-7973f154-efdf-479d-96d6-ecd8b64f7a77.png](https://user-images.githubusercontent.com/18387852/143019663-7973f154-efdf-479d-96d6-ecd8b64f7a77.png)

**This is just a reference, As mentioned before, It is not important and not necessary for the final application!**

**Comment by theolazian** [comment]
@findmoon I think your concern has already been addressed in [this post](https://stackoverflow.com/questions/31529772/how-to-set-app-icon-for-electron-atom-shell-app). I don't know ho to resolve that. I guess that as long as it works in production mode, it's all good!

As for your issue with ```squirrel.windows```, I never run into this problem.. Do you have the right icon format? What I do is providing an icon format for each plateform in my ```img``` folder like [so](https://github.com/aliceandbob-io/aliceandbob-desktop/tree/master/src/img). Then, when compiling, each platform will choose automatically the right icon:

```JS
//forge.config.js
...
packagerConfig: {
    icon: path.resolve(__dirname, 'src/img/icon'), // no extension here
    executableName: "aliceandbob.io"
  },
...
```

For squirrel and the ```iconUrl``` option, I specifically provide an url which points to an icon available publicly (i.e Github in this case). And for the ```setupIcon```, I also specifically provide the icon with the extension.

```JS
///forge.config.js
...
makers: [
    {
      name: "@electron-forge/maker-squirrel",
      config: {
        iconUrl: "https://raw.githubusercontent.com/aliceandbob-io/files/main/icon.ico", 
        setupIcon: path.resolve(__dirname, 'src/img/icon.ico') // extension provided here
      }
    },
...
```

Check also these links for more info maybe:
- [ting-platform-dependant-icon-via-electron-forge-electronpackagerconfig](https://stackoverflow.com/questions/48790003/setting-platform-dependant-icon-via-electron-forge-electronpackagerconfig)
- [how-to-set-the-app-icon-using-electron-forge-package-on-mac](https://stackoverflow.com/questions/44122559/how-to-set-the-app-icon-using-electron-forge-package-on-mac)
- [how-to-set-app-icon-for-electron-atom-shell-app](https://stackoverflow.com/questions/31529772/how-to-set-app-icon-for-electron-atom-shell-app)
- [this issue](https://github.com/onmyway133/blog/issues/66)

**Comment by findmoon** [comment]
@theolazian Thanks. It's all good as long as it works in production mode. I very agree with this opinion!

And, The setting of `packagerConfig.icon` without extension is a good way, it also mentioned in links that you gives.

So far, I had does not have any questions about the icon settings. 

Thank you for your answer and patient explanation!

**Comment by theolazian** [comment]
Awesome @findmoon! Happy to help! I'm closing this issue then 🚀
